local Command = require("utils.command")

Command.cmd({
		'syntax on',
		'colorscheme dracula',
		'set background=dark',
		'set termguicolors',
		'set number',
		'set relativenumber',
		'set title',
		'set tabstop=2',
		'set shiftwidth=2',
		'set expandtab',
		'set softtabstop=2',
		'set lazyredraw',
		'set background=dark',
		'set nowrap',
		'set noswapfile',
		'set cursorline',
		'set scrolloff=10',
		'set encoding=utf-8',
		'set nosc noru nosm',
		'set ignorecase',
		'set smarttab',
		'set ai',
		'set si',
		'set backspace=start,eol,indent',
		'set completeopt=menu,menuone,noselect',
		'filetype indent on',
		'filetype plugin on',
	})
